#ifndef ASR_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H
#define ASR_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H

#include <AutoStarRail/Core/ForeignInterfaceHost/Config.h>
#include <nlohmann/json.hpp>

ASR_CORE_FOREIGNINTERFACEHOST_NS_BEGIN

enum class ForeignInterfaceLanguage
{
    Python,
    CSharp,
    Java,
    Cpp,
    Lua
};

#define ASR_CORE_FOREIGNINTERFACEHOST_DEFAULT_ENUM_SERIALIZE(x) {ForeignInterfaceLanguage::x, #x}

NLOHMANN_JSON_SERIALIZE_ENUM(
    ForeignInterfaceLanguage,
    {ASR_CORE_FOREIGNINTERFACEHOST_DEFAULT_ENUM_SERIALIZE(Python),
     ASR_CORE_FOREIGNINTERFACEHOST_DEFAULT_ENUM_SERIALIZE(CSharp),
     ASR_CORE_FOREIGNINTERFACEHOST_DEFAULT_ENUM_SERIALIZE(Java),
     ASR_CORE_FOREIGNINTERFACEHOST_DEFAULT_ENUM_SERIALIZE(Cpp),
     ASR_CORE_FOREIGNINTERFACEHOST_DEFAULT_ENUM_SERIALIZE(Lua)});

ASR_CORE_FOREIGNINTERFACEHOST_NS_END

#endif // ASR_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H
